waver_amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.3
    alpha2: 0.1
    alpha3: 0.4
    alpha4: 0.1
    alpha5: 0.1
    always_reset_initial_pose: false
    base_frame_id: base_footprint
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: true
    first_map_only: false
    global_frame_id: map
    initial_pose.x: 0.0
    initial_pose.y: 0.0
    initial_pose.yaw: 0.0
    initial_pose.z: 0.0
    lambda_short: 0.05
    laser_likelihood_max_dist: 2.0
    laser_max_range: 10.0
    laser_min_range: 0.1
    laser_model_type: beam
    map_topic: map
    max_beams: 200
    max_particles: 1500
    min_particles: 500
    odom_frame_id: odom
    pf_err: 0.05
    pf_z: 0.95
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: nav2_amcl::DifferentialMotionModel
    save_pose_rate: 0.5
    scan_topic: scan
    set_initial_pose: false
    sigma_hit: 0.3
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.002
    update_min_d: 0.02
    z_hit: 0.9
    z_max: 0.05
    z_rand: 0.1
    z_short: 0.2
